/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package goa.systems.pdfmerge;

import java.io.File;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import goa.systems.pdfmerge.configuration.Configuration;
import goa.systems.pdfmerge.configuration.PdfAction;

public class App {

	private static final Logger logger = LoggerFactory.getLogger(App.class);

	public boolean execute(Configuration c) {
		logger.debug("Applying {} actions.", c.getActions().size());
		for (PdfAction pa : c.getActions()) {
			pa.apply(new File(c.getDestdir(), c.getDestfilename()));
		}
		return true;
	}

	public static void main(String[] args) {
		logger.info("App not yet finished.");
	}
}
