/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package goa.systems.pdfmerge;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import goa.systems.pdfmerge.control.Control;
import goa.systems.pdfmerge.control.CommandLineParser;
import goa.systems.pdfmerge.model.Configuration;

public class PdfMerge {

	private static final Logger logger = LoggerFactory.getLogger(PdfMerge.class);

	public static void main(String[] args) {
		CommandLineParser clp = new CommandLineParser();
		Configuration c = clp.parseCommandline(args);
		if (c != null) {
			Control a = new Control(c);
			a.execute();
		} else {
			logger.error("Error: Configuration error. Not all required values are provided.");
			logger.error("Use either '-j' with a json file specified or a combination of ");
			logger.error("'-s' '-a' '-d' '-f'. '-a' can occur mutliple times.");
		}
	}
}
